# Generated by Django 4.1.6 on 2023-02-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('project_url', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('project_first_pic', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('project_second_pic', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('project_third_pic', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('project_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
