# Generated by Django 3.2.17 on 2023-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default=None, help_text='Enter Your resume here', null=True, upload_to='resume/')),
            ],
        ),
    ]
