# Generated by Django 3.2.17 on 2023-02-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230211_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
