# Generated by Django 4.1.6 on 2023-02-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20230213_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="idea",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="launch",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="research",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
