# Generated by Django 4.1.6 on 2023-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_project_idea_project_launch_project_research_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
